### ISSUE TITLE
make it possible to readwrite from any `IO` object, not just files

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/Feather.jl#113]
Not sure why in the world I was stupid enough not to do this in the first place.  Very useful for, for example, writing to S3 buckets or other IO that doeshn't (or ideally wouldn't) directly involve the file system.

I should be able to get to it soon.

**Comment by dawbarton** [comment]
This is great! I just came looking for this feature to add compression to feather files.

**Comment by ExpandingMan** [comment]
The PR seems extremely stuck right now.  We seem to be getting a segfault in the container when testing loading the feather in python which I cannot reproduce anywhere else with the same files.  I'm wondering if it is a version issue with something in the container, but I can't update the container.
