### ISSUE TITLE
Incompatibility with Tables 1.0

### ISSUE THREAD

**Issue by palday** [JuliaData/Feather.jl#133]
Tables 1.0 breaks Feather. Using the `d3.feather` from the artifact that MixedModels uses for test data:

```julia
using MixedModels, Feather
julia> Feather.read(joinpath(MixedModels.TestData, "d3" * ".feather"))
ERROR: MethodError: no method matching eachcolumn(::NamedTuple{(:g, :h, :i, :u, :y),Tuple{Arrow.DictEncoding{String,Arrow.Primitive{Int32},Arrow.List{String,Int32,Arrow.Primitive{UInt8}}},Arrow.DictEncoding{String,Arrow.Primitive{Int32},Arrow.List{String,Int32,Arrow.Primitive{UInt8}}},Arrow.DictEncoding{String,Arrow.Primitive{Int32},Arrow.List{String,Int32,Arrow.Primitive{UInt8}}},Arrow.Primitive{Int8},Arrow.Primitive{Int8}}})
Closest candidates are:
  eachcolumn(::Union{Function, Type}, ::Tables.Schema{names,nothing}, ::Any) where names at /home/user/.julia/packages/Tables/erUMm/src/utils.jl:109
  eachcolumn(::Union{Function, Type}, ::Tables.Schema{names,types}, ::Any) where {names, types} at /home/user/.julia/packages/Tables/erUMm/src/utils.jl:66
```

**Comment by davidanthoff** [comment]
I thought Tables.jl 1.0 is non-breaking?

**Comment by palday** [comment]
Me too ....

**Comment by quinnj** [comment]
There were 3 functions that ended up being removed in the 1.0 release; `Tables.eachcolumn(columns)` which has been replaced with `Tables.Columns(columns)`, and `Tables.select`/`Tables.transform` were moved to the TableOperations.jl package.

Please note that there's nothing to be alarmed about here; Feather.jl correctly had Tables.jl compat on `"0.2.3"`. With a major release, nothing is auto-upgraded, so no users will actually see things "break". Once we implement 1.0 support in Feather, and tag a new release w/ `"1"` compat, everything will be fine.

**Comment by quinnj** [comment]
Also, feel free to checkout the [Discourse announcement](https://discourse.julialang.org/t/ann-tables-jl-1-0-release/34505) that did a more thorough walk-through of 1.0 release notes and upgrade guide for breaking changes.

**Comment by palday** [comment]
Not alarmed, just passing on hopefully useful info. :)

**Comment by CarloLucibello** [comment]
this can be closed
