### ISSUE TITLE
reading only a subset of columns

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/Feather.jl#36]
Obviously one can simply load the dataframe and select the desired columns, but I was wondering if there would be room for increasing performance when only a subset of columns is needed.  If I'm understanding the format correctly, I think the answer to this question is "yes", in which case it would be really nice if we could do something like
```julia
df = Feather.read("file.feather", columns=[:x1, :x2, :x4])
```
which would be useful on dataframes with large numbers of columns.

**Comment by quinnj** [comment]
Yep, definitely possible. I have some notes somewhere when I started to sketch this out for all of DataStreams. Let me try to find those notes and see about applying this generically across all packages.

**Comment by ExpandingMan** [comment]
Great, that'd be a really good feature.  It would be especially good if one could also select only a subset of rows.  For me this is really the only advantage that a database has over this type of format.  

By the way, I can deserialize an 11GB file in about 17s, so I don't have any real need to resort to another format until I reach like 60GB which is fantastic!

**Comment by ExpandingMan** [comment]
Another extremely important feature would be reading/writing only specific *rows* as well.  Is this possible?  I'm not even really sure whether this format is designed for that sort of thing.

**Comment by ExpandingMan** [comment]
So, I've been doing some exploring.  Right now it seems that @quinnj has implemented `Data.streamfrom(source, Data.Column, ...)` so that to read a column you can do, for instance,
```julia
src = Feather.Source(filename)
sch = Data.schema(src)

col = "A"
colnum = sch[col]
dtype = Data.types(sch)[colnum]
A = Data.streamfrom(src, Data.Column, Vector{dtype}, colnum)
```
However, if you attempt to use the method for reading single features `Data.streamfrom(src, Data.Field, ...)` what will happen is that the entire column will be read in and stored in the `Feather.Source`.  So, at the moment, one cannot read individual features.

**Comment by ExpandingMan** [comment]
This issue is no longer relevant.
