### ISSUE TITLE
DataTables compatibility

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/Feather.jl#41]
As I'm sure most people here know, the DataFrames repository has been split into DataFrames (with the `DataArray` backend) and DataTables (with the `NullableArray` backend).  DataTables looks pretty close to being ready for use (they've recently had a PR where they *finally* fixed the groupby performance, yay!), and, besides, those of use who have been using the previous DataFrames master (DataTables before it was named that) will have to switch to DataTables very soon.

Since Feather already accommodates the `NullableArray` backend, I don't think much has to be changed to make it work with DataTables (hopefully it's as simple as a search and replace).  Are there any plans for doing this?  I didn't see a branch for it.

If not, I'm going to have to do it myself soon, as I rely on this package a lot.  I'd be happy to make a PR, but I don't know how you guys want to handle making this compatible with both DataFrames and DataTables.

**Comment by quinnj** [comment]
DataTables has now been deprecated and improvements have been ported to DataFrames. DataFrames & Feather are now all based on `Vector{Union{Null, T}}`
