### ISSUE TITLE
FileIO registration

### ISSUE THREAD

**Issue by timholy** [JuliaData/Feather.jl#44]
Consider registering this package with [FileIO](https://github.com/JuliaIO/FileIO.jl), so that users don't have to know which package to install to interact with feather files. JLD's `load`/`save` implementations might be a useful model. (But don't extend `FileIO.load` etc, make it a non-exported function and FileIO will scope the call. JLD extends them for historical reasons.)

**Comment by quinnj** [comment]
Accomplished by @davidanthoff in https://github.com/davidanthoff/FeatherFiles.jl
