### ISSUE TITLE
Broken strings with unicode characters

### ISSUE THREAD

**Issue by msmidc** [JuliaData/Feather.jl#49]
When I store a DataFrame with non-ascii characters in it in Feather, and read it back, the string gets corrupted.
Steps to reproduce:
```
df = DataFrame(A = ["abc", "ñ", "def"])
Feather.write("test.feather", df)
Feather.read("test.feather")
```
It prints:
```
3×1 DataFrames.DataFrame
│ Row │ A      │
├─────┼────────┤
│ 1   │ "abc"  │
│ 2   │ "Ã"   │
│ 3   │ "±de" │
```

**Comment by quinnj** [comment]
Thanks for the report! There was a little cleanup we can do on the Feather side, but this was mostly a WeakRefStrings problem w/ a few of its definitions. It's been cleaned up over there now, so they should show correctly. Note that there was no actual corruption of data or anything, it was really just a "show" bug with WeakRefStrings.
