### ISSUE TITLE
Example does not run

### ISSUE THREAD

**Issue by Rudi79** [JuliaData/Feather.jl#50]
Hi, 
I try to run:

```
using Feather  
df = DataFrame(A = 1:4, B = ["M", "F", "F", "M"])
Feather.write("shiny_new_feather_file.feather", df)
```

It fails with: ArgumentError: `source` doesn't support the supported streaming types of `sink`: DataType[DataStreams.Data.Column, DataStreams.Data.Field]

I don't understand why this small code snippet isn't working. Any help is appreciated.

**Comment by ararslan** [comment]
Hey @Rudi79, could you post your `versioninfo()` and `Pkg.status("Feather")`?

**Comment by Rudi79** [comment]
Sure:
Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: Windows
 (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)

Pkg.status("Feather"): 
 - Feather                       0.2.5
Thx for looking into this issue.
Best, Rudi

**Comment by quinnj** [comment]
This now works on current master; sorry if things got a little out of sink
```julia
julia> using Feather, DataFrames

julia> df = DataFrame(A = 1:4, B = ["M", "F", "F", "M"])
4×2 DataFrames.DataFrame
│ Row │ A │ B │
├─────┼───┼───┤
│ 1   │ 1 │ M │
│ 2   │ 2 │ F │
│ 3   │ 3 │ F │
│ 4   │ 4 │ M │

julia> Feather.write("shiny_new_feather_file.feather", df)
Feather.Sink{DataFrames.DataFrameStream{Tuple{Array{Int64,1},Array{String,1}}}}(Feather.Metadata.CTable("", 4, Feather.Metadata.Column[Feather.Metadata.Column("A", Feather.Metadata.PrimitiveArray(INT64, PLAIN, 8, 4, 0, 32), 0, nothing, ""), Feather.Metadata.Column("B", Feather.Metadata.PrimitiveArray(UTF8, PLAIN, 40, 4, 0, 32), 0, nothing, "")], 2, ""), "shiny_new_feather_file.feather", IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1), "", "", DataFrames.DataFrameStream{Tuple{Array{Int64,1},Array{String,1}}}(([1, 2, 3, 4], String["M", "F", "F", "M"]), String["A", "B"]))

```
