### ISSUE TITLE
why padding?

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/Feather.jl#74]
I've been working on rewriting Feather with my new [Apache Arrow Implementation](https://github.com/ExpandingMan/Arrow.jl) and a [new version of Feather](https://github.com/ExpandingMan/Feather.jl/tree/arrow1) version for implementing it (still working, will document and request comments once I have the new Feather completely up and working with Arrow), and one thing I have been noticing is that it doesn't actually seem that the Feather [format](https://github.com/wesm/feather/blob/master/doc/FORMAT.md) requires any padding whatsoever.  Also, as far as I can tell everything seems to pretty much just work if all of the padding is removed.  What is the reason for the padding?  Is there some benefit?

**Comment by quinnj** [comment]
https://github.com/apache/arrow/blob/master/format/Layout.md#alignment-and-padding

**Comment by ExpandingMan** [comment]
Hm, that's embarrassing on my part as obviously I should have known that, but for some reason I could have *sworn* that this was optional...
