### ISSUE TITLE
Improve Error Message When Data Type is Not Supported (Or Convert)

### ISSUE THREAD

**Issue by iwelch** [JuliaData/Feather.jl#98]
I just had a weird error

```
julia> Feather.write(filename, df)
ERROR: KeyError: key Char not found
```

eventually, it dawned on me that my data frame had a char column, and that this was the problem.

so, I would suggest

1. character to string auto-conversion (and other suitable auto-conversion)
2. a message like "column x (named 'n') is type T, which is not supported by Feather"

I hope that both are easy fixes.

**Comment by iwelch** [comment]
hi EM.  just wanted to suggest little improvements as I am playing around with it.  feel free to close.  best, /iaw

**Comment by ExpandingMan** [comment]
At a minimum at some point we will improve the error messages, so I won't close this issue until that happens.

**Comment by cstjean** [comment]
Feather does not support storing `Rational`s, like `1//2`. In that case, a conversion to Float64 would have been nice.

**Comment by ExpandingMan** [comment]
Some conversions would definitely be nice (we already have `TimeType` conversions), but we should proceed carefully.  For example, I don't think that `Rational` should be automatically converted, as rationals are exact while floating point is not.

**Comment by ExpandingMan** [comment]
I'm going to close this issue since it's specifically about an error message that has now been implemented.  Feel free to open new issues about conversions.
